name: physio_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  dropdown_button2: ^3.1.0
  flutter:
    sdk: flutter
  google_fonts: ^8.1.0
  intl: ^0.20.2
  http: ^1.2.1
  flutter_secure_storage: ^9.2.1
  socket_io_client: ^3.0.1
  flutter_local_notifications: ^17.2.1
  shared_preferences: ^2.5.5
  pedometer: ^4.0.1
  permission_handler: ^12.0.1
  heart_bpm: ^2.0.0+0
  hugeicons: ^1.1.6
  url_launcher: ^6.3.2
  pdf: ^3.12.0
  printing: ^5.14.3
  fl_chart: ^1.2.0
  connectivity_plus: ^7.1.1
  flutter_blue_plus: ^2.3.2
  flutter_blue_plus_winrt: ^0.0.20
  image_picker: ^1.2.2
  image_cropper: ^12.2.1
  path_provider: ^2.1.6
  google_generative_ai: ^0.4.7
  flutter_markdown: ^0.7.7+1
  file_picker: ^11.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/
